### ISSUE TITLE
Does not allow pressure-vessel to mount container runtimes from a non-default Steam Library

### ISSUE THREAD

**Issue by smcv** [canonical/steam-snap#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

https://github.com/ValveSoftware/steam-runtime/issues/602

The user reported that they have "Steam Linux Runtime - sniper" installed in `/media/myrmidon/Linux Games/Steam Library/steamapps/common/SteamLinuxRuntime_sniper`.

Launching a Proton 8.0 game fails with:

```
bwrap: Can't bind mount
/oldroot/media/myrmidon/Linux Games/Steam Library/
steamapps/common/SteamLinuxRuntime_sniper/var/tmp-9T0171/usr
 on /newroot/usr: Unable to mount source on destination: Permission denied
```

(newlines added for readability, in the real log file this is a single long line)

### Expected Behavior

If Canonical is going to package Steam as a snap, then it should allow pressure-vessel to bind-mount the container runtime /usr from at least the most common locations for a Steam library.

Locations below `/home/` are already allowed by `mount options=(rw, rbind) /oldroot/home/**/usr/ -> /newroot/usr/,` plus some related lines for `usr/etc`.

There should be similar expressions replacing `/home/` with `/media/`, `/mnt/`, `/run/media/`. It would be OK to limit these to something like `/oldroot/media/**/steamapps/common/**/usr` if desired, but please don't go any more specific than that, to avoid relying on implementation details that would make this Snap even more fragile than it already is.

For completeness, maybe `/opt/`, `/srv/` should also be allowed.

### Steps To Reproduce

Untested because I'm forwarding someone else's issue report, but these steps should reproduce the issue:

* Set up a Steam Library on a non-default disk (in `/media`, `/mnt/`, `/run/media/` or a similar location)
* Install "Steam Linux Runtime - soldier" and/or "Steam Linux Runtime - sniper"
* [Use Steam's UI](https://help.steampowered.com/en/faqs/view/4BD4-4528-6B2E-8327#move) to move them into that Steam Library if they are not already there
* For soldier, launch a Windows game that uses Proton 5.13, 6.3 or 7.0, or a native Linux game that has been forced to use the "Steam Linux Runtime" compatibility tool
* For sniper, launch a Windows game that uses Proton 8.0 or Experimental, or one of a few native Linux games that use sniper: Dota 2, Endless Sky, Retroarch

### Environment

```yaml
(not available, I'm forwarding someone else's issue report)
```

**Comment by smcv** [comment]
This is probably the root cause of #126, and possibly some of the launch failures in #27 (although not necessarily all of them).

I've reported it as a separate issue to avoid user reports of similar symptoms happening for different reasons getting mixed together.

**Comment by ashuntu** [comment]
This should be resolved by https://github.com/snapcore/snapd/pull/13053.

**Comment by ssrhunter** [comment]
It appears as though I may be running into this issue while using Ubuntu 22.04.3 LTS and snap 2.60.4 with
snapd 2.60.4.

`bwrap: Can't bind mount /oldroot/media/user/storage/games/steam/steamapps/common/SteamLinuxRuntime_sniper/var/tmp-OK5BG2/usr on /newroot/usr: Unable to mount source on destination: Permission denied`

Is it possible to get the latest fixes that have been applied since this ticket was closed, or do I need to wait for a newer build of snapd to appear on the official Ubuntu repositories?

**Comment by ssrhunter** [comment]
I upgraded to the latest beta version of snapd 2.61.1 but I still get the following error:

`pressure-vessel-wrap[7803]: W: "snap/steam/154/graphics/usr/share/libdrm" is unlikely to appear in "/run/host"
pressure-vessel-wrap[7803]: W: "snap/steam/154/graphics/usr/share/libdrm" is unlikely to appear in "/run/host"
pressure-vessel-wrap[7803]: W: "var/lib/snapd/hostfs/usr/share/drirc.d" is unlikely to appear in "/run/host"
pressure-vessel-wrap[7803]: W: "snap/steam/154/graphics/usr/share/drirc.d" is unlikely to appear in "/run/host"
pressure-vessel-wrap[7803]: W: "var/lib/snapd/hostfs/usr/share/nvidia" is unlikely to appear in "/run/host"
pressure-vessel-wrap[7803]: W: "var/lib/snapd/hostfs/usr/share/nvidia" is unlikely to appear in "/run/host"
bwrap: Can't bind mount /oldroot/etc/drirc on /newroot/etc/drirc: Unable to mount source on destination: Permission denied
Uploaded AppInterfaceStats to Steam
`

**Comment by smcv** [comment]
This is a closed issue, so please open a separate issue for at least this new problem:

> `bwrap: Can't bind mount /oldroot/etc/drirc on /newroot/etc/drirc: Unable to mount source on destination: Permission denied`

**Comment by ssrhunter** [comment]
Ok, thanks.
