### ISSUE TITLE
NVidia GPU Driver Upgrade: Missing "libGLX_nvidia.so.0" and "libEGL_nvidia.so.0" dependencies

### ISSUE THREAD

**Issue by ErickLandowski** [canonical/steam-snap#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

Every time I upgrade the GPU Drivers ( NVidia RTX 3050 Mobile ) Steam Snap fails to launch basically any game that runs under Proton. It won't even launch the game. Linux native games run fine.

Today the same thing happened after upgrading to "535.104.05". 

It only happens with Steam Snap, and looks like the only way to have it working back again is if i completely **reinstall** Steam Snap and all its games. Unless there is a way to make it work, which i'm not aware of.

I have Steam Flatpak installed and it works with no issues.

### Expected Behavior

The games running on Proton should work after upgrading GPU drivers, without the need to reinstall Steam snap completely.

### Steps To Reproduce

1) Update Nvidia Drivers
2) Reboot laptop/desktop
3) Refresh Steam snap
4) Launch Steam Proton Game (with no success)

### Environment

```yaml
os_release:
    name:               "Ubuntu"
    version:            "23.04 (Lunar Lobster)"
snap_info:
    steam_revision:     165
    snapd_revision:     20092
lspci:
    01:00.0:            NVIDIA Corporation GA107M [GeForce RTX 3050 Mobile] (rev a1)
    06:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Cezanne (rev c5)
glxinfo:
    gpu:                RENOIR (renoir, LLVM 15.0.7, DRM 3.49, 6.2.0-33-generic)
    gpu_version:        4.6 (Core Profile) Mesa 23.1.7 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 7 5800H with Radeon Graphics
xdg_current_desktop:    ubuntu:GNOME
desktop_session:        ubuntu
```

### Anything else?

[snap-logs.txt](https://github.com/canonical/steam-snap/files/12731279/snap-logs.txt)

**Comment by ashuntu** [comment]
After you reinstall Steam, does it work correctly with the updated drivers?

If it happens again, try running `sudo /usr/lib/snapd/snap-discard-ns steam` in a terminal after you upgrade your drivers and let us know if it allows Steam to work. Failing that, try rebooting your computer and see if that fixes it.

**Comment by kenvandine** [comment]
Note if the snap-discard-ns trick does resolve the issue, then that will actually be fixed in the snapd 2.61 release

**Comment by ErickLandowski** [comment]
Hi Ash,

Yes when i reinstall Steam it always worked. I didn't reinstall it yet, but I can do it once you guys have enough info from the troubleshooting.

Regarding your command, it didn't return anything:

`erick@erick-Nitro-AN515-45:~$ sudo /usr/lib/snapd/snap-discard-ns steam
erick@erick-Nitro-AN515-45:~$ `
Testing with no sudo:

`erick@erick-Nitro-AN515-45:~$ /usr/lib/snapd/snap-discard-ns steam
cannot set effective group to 0: Operation not permitted`

But just running "steam" works:

`erick@erick-Nitro-AN515-45:~$ steam
Testing for explicit PulseAudio choice...
...and PulseAudio has been explicitly chosen, so using it.
steam.sh[23502]: Running Steam on ubuntu 23.04 64-bit
steam.sh[23502]: STEAM_RUNTIME is enabled automatically
setup.sh[23636]: Steam runtime environment up-to-date!
Found NVIDIA version: 535.104.05
Need NVIDIA 32-bit: False
steam.sh[23502]: Steam client's requirements are satisfied
[2023-09-26 17:21:43] Startup - updater built Sep 11 2023 20:48:54
[2023-09-26 17:21:43] Startup - Steam Client launched with: '/home/erick/snap/steam/common/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox'`

In case it may be anything useful, below is a linux-native game running:

`erick@erick-Nitro-AN515-45:~$ nvidia-smi 
Tue Sep 26 17:25:57 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    Off | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P3              18W /  60W |    150MiB /  4096MiB |     38%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2077      G   /usr/lib/xorg/Xorg                           34MiB |
|    0   N/A  N/A     25009      G   ... of Eternity II/PillarsOfEternityII      106MiB |
+---------------------------------------------------------------------------------------+
erick@erick-Nitro-AN515-45:~$ `

Since I haven't reinstalled Steam snap yet, let me know if there is any other info I could get to help.

Thank you!

**Comment by ashuntu** [comment]
`snap-discard-ns` *shouldn't* return anything, so that's good. And like Ken said, it should be fixed in snapd in 2.61 without having to run the command.

I'm willing to bet that just running that command should resolve the issue with the Steam Snap, so let us know if it works. If it does work, it would be something you have to run every time you update your drivers, until snapd is updated (you can check your version with `snap info snapd`).

**Comment by ErickLandowski** [comment]
I've also rebooted my laptop and tried launching Steam on top of my dedicated GPU (i could see Steam listed via "nvidia-smi" but it still won't launch any game via Proton. Only linux native works:

Below is Steam launched via dedicated GPU, and Linux Native game running. For Steam proton game, the same problem persists.

```shell
erick@erick-Nitro-AN515-45:~$ nvidia-smi
Tue Sep 26 17:49:33 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    Off | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P0              36W /  60W |    289MiB /  4096MiB |     47%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2130      G   /usr/lib/xorg/Xorg                           84MiB |
|    0   N/A  N/A      6549      G   ...re/Steam/ubuntu12_64/steamwebhelper        2MiB |
|    0   N/A  N/A      6600      G   ...eam/logs/cef_log.txt --shared-files       96MiB |
|    0   N/A  N/A      7123      G   ... of Eternity II/PillarsOfEternityII       94MiB |
+---------------------------------------------------------------------------------------+
erick@erick-Nitro-AN515-45:~$ 

```

**Comment by ashuntu** [comment]
And for it to work again, it requires you to fully purge the snap with `--purge`? Or can you do a simple uninstall and reinstall?

**Comment by ErickLandowski** [comment]
> And for it to work again, it requires you to fully purge the snap with `--purge`? Or can you do a simple uninstall and reinstall?

Hello Ashuntu,

No need to "--purge". I can create a snapshot manually (or let Snap do that for me when uninstalling), and after a new installation just restore the snapshot.

I did this today (i created a snapshot, removed Steam snap, reinstalled and restored the snapshot), and this procedure worked:

```shell
erick@erick-Nitro-AN515-45:~$ nvidia-smi 
Wed Sep 27 15:16:05 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    Off | 00000000:01:00.0 Off |                  N/A |
| N/A   53C    P0              59W /  60W |   2009MiB /  4096MiB |     99%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2034      G   /usr/lib/xorg/Xorg                           44MiB |
|    0   N/A  N/A     11897    C+G   ...punk 2077\bin\x64\Cyberpunk2077.exe     1945MiB |
+---------------------------------------------------------------------------------------+
erick@erick-Nitro-AN515-45:~$ 
``` 

But as I mentioned before, I have to reinstall Steam Snap every single time I do a GPU driver upgrade in order to get games running under Proton. Linux native doesn't show this behavior.

**Comment by lc-nyovchev** [comment]
I am experiencing the same problem. Every time I update `nvidia` gpu drivers on `ubuntu`, my `snap` `steam` installation stops working.

That doesn't seem to be the case for `apt` installed `steam`, so I attribute it to the proton directory structure in snap not being able to handle drivers update based on paths.

**Comment by ErickLandowski** [comment]
Hello @ashuntu, i think that so far this issue has been fixed and can be closed? 

It's been a long time since i faced this problem and it never appeared again after one of the Steam snap updates. Perhaps the other Issues that had been opened and are related to the incorrect path to the driver versions can be closed as well? Unless you guys still need this open to keep track of something?

**Comment by kenvandine** [comment]
Thanks!
